-
   description: Best Paper Committee, NAACL 2025
-
   description: Member of the Responsible AI (RAI) Academic Council, DoD Chief Digital and Artificial Intelligence Office (CDAO). 
-
   description: General Chair for ACL 2017
-
   description: Program Co-Chair for EMNLP 2015
-
   description: Chair of the NAACL Executive Board 2012-2013
-
   description: Secretary-Treasurer for SIGDAT (EMNLP) 2016-2018
-
   description: Sponsorship Director for ACL, 2020-present
-
   description: Board Member for NAACL Executive Board 2010-2015
-
   description: Action Editor for Transactions of the Association for Computational Linguistics 2012-2016
-
   description: Editorial Board for Computational Linguistics 2010-2012
-
   description: Program Committee Member, Area Chair, and/or Senior Area Chair for ACL, NAACL, EMNLP, COLING 
-
   description: Test of Time Award Committee, ACL 2020
-
   description: Best Paper Committee, ACL 2020
-
   description: Board Member for American Machine Translation Association 2009-2010
-
   description: North American Representative for ACL Special Interest Group in Machine Translation 2009-2010 
-
   description: Co-Organizer of the Workshop on Statistical Machine Translation 2007-2013